disabled_rules:
  - closure_parameter_position
  - cyclomatic_complexity
  - file_length
  - force_cast
  - function_body_length
  - nesting
  - todo
  - type_body_length
  - for_where
  - no_fallthrough_only
  # All the following Handled by SwiftFormat.
  - closure_end_indentation
  - closure_spacing
  - explicit_init
  - literal_expression_end_indentation
  - operator_usage_whitespace
  - private_over_fileprivate
  - redundant_void_return
  - return_arrow_whitespace
  - trailing_comma
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - vertical_whitespace
  - implicit_return

opt_in_rules:
  - array_init
  - block_based_kvo
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_direct_init
  - duplicate_imports
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - extension_access_modifier
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - multiline_parameters
  - multiple_closures_with_trailing_closure
  - nimble_operator
  - overridden_super_call
  - prefer_self_type_over_type_of_self
  - private_unit_test
  - prohibited_super_call
  - protocol_property_accessors_order
  - redundant_nil_coalescing
  - redundant_set_access_control
  - unneeded_parentheses_in_closure_argument

analyzer_rules:
  - unused_import
  - unused_declaration

indentation: 4

weak_delegate: error

function_parameter_count:
  warning: 8
  error: 8

large_tuple:
  warning: 3
  error: 3

identifier_name:
  min_length: 0
  max_length: 42

type_name:
  max_length: 52

line_length: 200

excluded:
  - .build
